name: vartracker
channels:
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - python=3.11.8
  - snakemake=9.0.1
  - bcftools=1.21
  - samtools=1.21
  - htslib=1.21
  - fastp=0.23.4
  - bwa=0.7.17
  - lofreq=2.1.5
  - pip
